name: Fetch Meta Ads CSV

on:
  schedule:
    - cron: '0 * * * *'  # 毎時実行
  workflow_dispatch:  # 手動実行も可能

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    - name: Pythonをセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 依存関係をインストール
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: スクリプトを実行
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        AD_ACCOUNT_ID: ${{ secrets.AD_ACCOUNT_ID }}
      run: |
        python meta_ads_to_csv.py

    - name: CSVファイルをGitHubにコミット
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add *.csv || true
        git commit -m "Add generated CSV from Meta Ads API" || echo "No changes to commit"
        git push
